env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:prettier/recommended
plugins:
  - prettier
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: [./tsconfig.json]
rules:
  "@typescript-eslint/consistent-type-imports": "off"
  "@typescript-eslint/strict-boolean-expressions":
    - error
    - allowNullableObject: true
  "@typescript-eslint/return-await":
    - error
    - in-try-catch
  "@typescript-eslint/explicit-function-return-type": "off"
  "@typescript-eslint/restrict-template-expressions": "off"
