[package]
name = "ephemeral-vrf-sdk"
description = "Ephemeral Vrf Integration SDK"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[features]
default = []
anchor = ["anchor-modern"]
anchor-modern = ["anchor-support", "anchor-lang-current"]
anchor-compat = ["anchor-support", "backward-compat", "anchor-lang-compat"]
anchor-support = []
backward-compat = [
    "borsh-compat",
    "solana-program-compat",
    "solana-pubkey-compat",
]

[dependencies]
anchor-lang-compat = { workspace = true, optional = true }
anchor-lang-current = { workspace = true, optional = true }
borsh-compat = { package = "borsh", version = "0.10.4", optional = true }
borsh-current = { package = "borsh", version = "1.5.7", features = ["derive"] }
solana-program = { workspace = true, features = ["borsh"] }
solana-program-compat = { workspace = true, optional = true }
solana-pubkey-compat = { package = "solana-pubkey", version = ">=2.0, <3", features = [
    "borsh",
    "bytemuck",
    "curve25519",
], optional = true }
solana-system-interface = { workspace = true }
