/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  type Codec,
  type Decoder,
  type Encoder,
  type Option,
  type OptionOrNullable,
} from "@solana/kit";
import {
  getMemberDecoder,
  getMemberEncoder,
  type Member,
  type MemberArgs,
} from ".";

export interface MembersArgs {
  members: Option<Member[]>;
}

export interface MembersArgsArgs {
  members: OptionOrNullable<MemberArgs[]>;
}

export function getMembersArgsEncoder(): Encoder<MembersArgsArgs> {
  return getStructEncoder([
    ["members", getOptionEncoder(getArrayEncoder(getMemberEncoder()))],
  ]);
}

export function getMembersArgsDecoder(): Decoder<MembersArgs> {
  return getStructDecoder([
    ["members", getOptionDecoder(getArrayDecoder(getMemberDecoder()))],
  ]);
}

export function getMembersArgsCodec(): Codec<MembersArgsArgs, MembersArgs> {
  return combineCodec(getMembersArgsEncoder(), getMembersArgsDecoder());
}
