/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from '@solana/kit';

// Flags for Member
export const MEMBER_FLAG_DEFAULT: number = 0;
export const MEMBER_FLAG_AUTHORITY: number = 1 << 0; // Member has authority privileges
export const MEMBER_FLAG_TX_LOGS: number = 1 << 1; // Member can see transaction logs
export const MEMBER_FLAG_TX_BALANCES: number = 1 << 2; // Member can see transaction balances

export type Member = { flags: number; pubkey: Address };

export type MemberArgs = Member;

export function getMemberEncoder(): FixedSizeEncoder<MemberArgs> {
  return getStructEncoder([
    ['flags', getU8Encoder()],
    ['pubkey', getAddressEncoder()],
  ]);
}

export function getMemberDecoder(): FixedSizeDecoder<Member> {
  return getStructDecoder([
    ['flags', getU8Decoder()],
    ['pubkey', getAddressDecoder()],
  ]);
}

export function getMemberCodec(): FixedSizeCodec<MemberArgs, Member> {
  return combineCodec(getMemberEncoder(), getMemberDecoder());
}

/**
 * Check if a member is an authority for a given user
 */
export function isAuthority(member: Member, user: Address): boolean {
  return (
    (member.flags & MEMBER_FLAG_AUTHORITY) !== 0 &&
    member.pubkey === user
  );
}

/**
 * Check if a member can see transaction logs for a given user
 */
export function canSeeTxLogs(member: Member, user: Address): boolean {
  return (
    (member.flags & MEMBER_FLAG_TX_LOGS) !== 0 && member.pubkey === user
  );
}

/**
 * Check if a member can see transaction balances for a given user
 */
export function canSeeTxBalances(member: Member, user: Address): boolean {
  return (
    (member.flags & MEMBER_FLAG_TX_BALANCES) !== 0 &&
    member.pubkey === user
  );
}

