/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getArrayDecoder,
  getArrayEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type Codec,
  type Decoder,
  type Encoder,
} from '@solana/kit';

export type UndelegateArgs = { pdaSeeds: Array<Array<number>> };

export type UndelegateArgsArgs = UndelegateArgs;

export function getUndelegateArgsEncoder(): Encoder<UndelegateArgsArgs> {
  return getStructEncoder([
    ['pdaSeeds', getArrayEncoder(getArrayEncoder(getU8Encoder()))],
  ]);
}

export function getUndelegateArgsDecoder(): Decoder<UndelegateArgs> {
  return getStructDecoder([
    ['pdaSeeds', getArrayDecoder(getArrayDecoder(getU8Decoder()))],
  ]);
}

export function getUndelegateArgsCodec(): Codec<
  UndelegateArgsArgs,
  UndelegateArgs
> {
  return combineCodec(getUndelegateArgsEncoder(), getUndelegateArgsDecoder());
}
