[package]
name = "ephemeral-rollups-sdk-v2"
description = "Ephemeral Rollups Integration SDK"
version = { workspace = true }
authors = { workspace = true }
repository = { workspace = true }
documentation = { workspace = true }
homepage = { workspace = true }
keywords = { workspace = true }
readme = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[features]
default = []
anchor = ["anchor-lang"]

[dependencies]
borsh = { workspace = true }
ephemeral-rollups-sdk-attribute-delegate-v2 = { workspace = true }
ephemeral-rollups-sdk-attribute-ephemeral-v2 = { workspace = true }
ephemeral-rollups-sdk-attribute-commit-v2 = { workspace = true }
paste = { workspace = true }
solana-program = { workspace = true }
anchor-lang = { workspace = true, optional = true }
