name: Magic Lab Project Automation

on:
  issues:
    types: [opened, reopened, transferred, labeled, unlabeled]
  pull_request:
    types: [opened, reopened, labeled, closed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  magic-lab:
    name: Update Magic Lab
    uses: magicblock-labs/.github/.github/workflows/magic_lab_automation.yml@21cae0c2ecb071828423f673076e887f8a5fe63d
    secrets:
      ADD_TO_PROJECT_PAT: ${{ secrets.ADD_TO_PROJECT_PAT }}
